language: android
sudo: false
jdk:
  #- oraclejdk8
  - openjdk8
android:
  components:
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
script:
  - ./gradlew assembleDebug
