# This workflow will build a package using Gradle and then publish it to maven local when a release is created
# See https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# and https://github.com/actions/starter-workflows/blob/master/ci/gradle-publish.yml

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      #- name: Publish to mavenLocal()
      #  run: ./gradlew publishToMavenLocal --warning-mode all
      - name: Publish to local maven repository
        run: ./gradlew publishReleasePublicationToLocal --warning-mode all
