# This workflow will build a package using Gradle and then publish it to maven local when a release is created
# See https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# and https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      #- name: Publish to mavenLocal()
      #  run: ./gradlew publishToMavenLocal --warning-mode all
      - name: Publish to local maven repository
        run: ./gradlew clean publishReleasePublicationToLocalRepository --info --warning-mode all
      - uses: actions/upload-artifact@v2
        with:
         name: Store Android Archive
         path: ../归档/
         
